import { Dispatch, SetStateAction } from 'react';
import { Courses } from './courses';
import { Students } from './students';

export type DepartmentContextType = {
   courses: Courses[];
   students: Students[];
   filteredStudents: Students[];
   fetchingStudents: boolean;
   courseId: string | null;
   setCourseId: Dispatch<SetStateAction<string | null>>;
   sectionId: string | null;
   setSectionId: Dispatch<SetStateAction<string | null>>;
   activeCourseId: string | null;
   selectedCourse: Courses;
   activeSectionId: string | null;
   clearanceId: string[];
   setClearanceId: Dispatch<SetStateAction<string[]>>;
   selectedStudents: Students[];
   effectiveStatus: string;
   statusFilter: string;
   setStatusFilter: Dispatch<SetStateAction<string>>;
   orderFilter: string;
   setOrderFilter: Dispatch<SetStateAction<string>>;
   departmentName?: string;
   userId?: string;
   viewType: 'students' | 'staff';
   setViewType: Dispatch<SetStateAction<'students' | 'staff'>>;
   prereqStatus: Map<string, boolean>;
   eligibleCount: number;
   sectionEligibleCounts: Record<string, number>;
   hasStaffTemplates: boolean;
};
