CREATE POLICY "department staff can view users" ON "users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff']);--> statement-breakpoint
CREATE POLICY "admin can manage users" ON "users" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']);--> statement-breakpoint
ALTER POLICY "admin can make changes" ON "clearance_departments" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']);--> statement-breakpoint
ALTER POLICY "department staff can make changes" ON "clearance_logs" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff']) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff']);--> statement-breakpoint
ALTER POLICY "department staff can view clearance records" ON "clearance_records" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff']);--> statement-breakpoint
ALTER POLICY "department staff can update clearance records" ON "clearance_records" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND template_id IN (SELECT template_id FROM public.clearance_templates WHERE staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid()))) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND template_id IN (SELECT template_id FROM public.clearance_templates WHERE staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid())));--> statement-breakpoint
ALTER POLICY "admin can manage clearance records" ON "clearance_records" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']);--> statement-breakpoint
ALTER POLICY "users can view own tasks" ON "clearance_tasks" TO authenticated USING ((clearance_id IN (SELECT clearance_id FROM public.clearance_records WHERE user_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid()))) OR ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid())));--> statement-breakpoint
ALTER POLICY "department staff can manage assigned tasks" ON "clearance_tasks" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid())) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid()));--> statement-breakpoint
ALTER POLICY "admin can make changes" ON "clearance_templates" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Admin']);--> statement-breakpoint
ALTER POLICY "department staff can manage their own predefined tasks" ON "staff_predefined_tasks" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid())) WITH CHECK ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff'] AND staff_id IN (SELECT user_id FROM public.users WHERE auth_id = auth.uid()));--> statement-breakpoint
ALTER POLICY "department staff can view students" ON "students" TO authenticated USING ((auth.jwt() -> 'user_metadata' -> 'custom_claims' -> 'roles') ?| ARRAY['Department', 'Staff']);